'use client';
import Link from 'next/link';

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-white text-zinc-900 font-sans">
      <nav className="border-b border-zinc-100 py-6 px-8">
        <Link href="/" className="text-xl font-black tracking-tighter">
          GREENCCV<span className="text-emerald-600">.</span>
        </Link>
      </nav>

      <article className="max-w-3xl mx-auto px-6 py-20">
        <h1 className="text-4xl font-black tracking-tight mb-4">Privacy Policy</h1>
        <p className="text-zinc-400 text-xs font-bold uppercase tracking-widest mb-12">Effective: April 20, 2026</p>

        <div className="space-y-10 text-zinc-600 leading-relaxed">
          <section className="space-y-4">
            <h2 className="text-lg font-black text-zinc-950 uppercase tracking-tight">1. Local-Only Processing</h2>
            <p>
              GreenCCV is a <strong>client-side only</strong> utility. We do not store, transmit, or collect any data you enter into our generator. All cardholder names, bank selections, and generated numbers are processed locally in your browser's memory and are destroyed when you close the tab.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-black text-zinc-950 uppercase tracking-tight">2. Image Generation</h2>
            <p>
              The PNG assets generated by this tool are created using your local hardware resources. No images are uploaded to our servers or stored in our databases.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-black text-zinc-950 uppercase tracking-tight">3. Advertising & Cookies</h2>
            <p>
              We use third-party advertising partners (such as Google AdSense) to serve advertisements. These partners may use cookies to serve ads based on your visit to this and other websites. You can manage your ad preferences through your browser settings or Google's ad settings page.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-lg font-black text-zinc-950 uppercase tracking-tight">4. Safety</h2>
            <p>
              We do not collect sensitive information such as IP addresses or location data for tracking purposes beyond what is required by our advertising partners for compliance and fraud prevention.
            </p>
          </section>
        </div>

        <div className="mt-20 pt-10 border-t border-zinc-100 text-center">
          <Link href="/" className="text-sm font-black text-emerald-600 hover:underline">
            Back to Generator
          </Link>
        </div>
      </article>
    </main>
  );
}